export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';

export const DECREASE_PRODUCT_AMOUNT = 'DECREASE_PRODUCT_AMOUNT';
export const INCREASE_PRODUCT_AMOUNT = 'INCREASE_PRODUCT_AMOUNT';

export const UPDATE_TOTAL = 'UPDATE_TOTAL'
export const SEND_FILTERED_PRODUCTS = 'SEND_FILTERED_PRODUCTS'
